mods:
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-mongo # Requires running mongodb and redis (provided in docker-compose)
  - screepsmod-bots
  - screepsmod-history
  - screepsmod-stats
  - screepsmod-visualize
  - screepsmod-dynamicmarket
  - screepsmod-features
  - screepsmod-portals
  - screepsmod-timeout
  - "@admon-dev/screepsmod-speedrun"
  - "@brisberg/screepsmod-lockstep"
  - "@screepsmod/serverinfo"
  - screepsmod-gcltocpu

pinnedPackages:
  ssri: 8.0.1
  cacache: 15.3.0
  passport-steam: 1.0.17
  minipass-fetch: 2.1.2
  express-rate-limit: 6.7.0
  yaml: 2.0.0-11

bots:
  overmind: screeps-bot-overmind
  toolangle: screeps-bot-tooangel # Username aligns with your bots.yml entry
  choreographer: screeps-bot-choreographer
  simplebot: "@screeps/simplebot"
  screeps-gpt: "https://github.com/ralphschuler/.screeps-gpt"

serverConfig:
  welcomeText: |
    <div style="text-align:center">
      <h1>My Screeps Private Server</h1>
      <p>Running with screeps-launcher + Mongo + Redis</p>
    </div>
  constants: {}
  tickRate: 100
