serverConfig: 
  tickRate: 200
  socketUpdateRate: 200
  shardName: 'test'
  constants:
    UPGRADE_POWER: 10
    POWER_CREEP_SPAWN_COOLDOWN: 3600000 # 1 Hour
    POWER_CREEP_DELETE_COOLDOWN: 3600000
  welcomeText: |
    <h1>Welcome</h1>
    <div>Powered by screepsmod-admin-utils</div>
  gclToCPU: true
  maxCPU: 100
  baseCPU: 20
  stepCPU: 10
