services:
  screeps:
    build: server
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 21025:21025/tcp
    volumes:
      - ./config.yml:/screeps/config.yml
      - ./bots.yml:/screeps/bots.yml
      - ./.screepsrc:/screeps/.screepsrc
      - screeps-data:/data
      - screeps-mods:/screeps/mods
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
      MAPTOOL_USER: admin
      MAPTOOL_PASS: ${MAPTOOL_PASSWORD:="superSecret"}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:21025/api/version || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 180s
      retries: 6

  mongo:
    image: mongo:8
    platform: linux/amd64
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", 'echo ''db.runCommand("ping").ok'' | mongosh mongo:27017/test --quiet']
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6

  redis:
    image: redis:7
    platform: linux/amd64
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      start_period: 5s
      retries: 6

volumes:
  screeps-data:
  screeps-mods:
  redis-data:
  mongo-data:
